mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/votes/', views.votes, name='votes'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

# Create your models here.

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse

def index(request):
    list_of_question = Question.objects.order_by('-pub_date')
    context = {'list_of_question' : list_of_question}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        q = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question Does not exists")
    return render(request, 'polls/detail.html', {'q' : q})

def results(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'q' : q})

def votes(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'q' : q, 'error_message' : "Select an option"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

# Create your views here.

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Details for {{ q.question_text }}</title>
</head>

<body>
    <header>
        <h1>Votes for {{ q.question_text }}</h1>
    </header>
    <main>
        <a href="{% url 'polls:results' q.id %}"><button>View Results</button></a><br />
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'polls:votes' q.id %}" method="POST">
            {% csrf_token %}
            {% for c in q.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ c.id }}" />
            <label for="choice{{ forloop.counter }}">{{ c.choice_text }}</label>
            <br />
            {% endfor %}
            <input type="submit" value="Vote" />
        </form>
    </main>
    <footer>
        <p>Written by Aditya Joshi &copy; Joshi's</p>
    </footer>
</body>

</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Questions Page</title>
</head>

<body>
    <header>
        <h1>Welcome to django Polling App</h1>
    </header>
    <main>
        <h2>Questions</h2>
        {% if list_of_question %}
        <ul>
            {% for q in list_of_question %}
            <li><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></li>
            {% endfor %}
        </ul>

        {% else %}
        <p>Sorry, No polls available</p>

        {% endif %}
    </main>
    <footer>
        <p>Written by Aditya Joshi &copy; Joshi's</p>
    </footer>
</body>

</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Results for {{ q.question_text }}</title>
</head>

<body>
    <header>
        <h1>Votes for {{ q.question_text }}</h1>
    </header>
    <main>
        <ul>
            {% for c in q.choice_set.all %}
            <li>{{ c.choice_text }} -- {{ c.votes }} Vote{{ c.votes|pluralize }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:detail' q.id %}">Vote Again??</a>
    </main>
    <footer>
        <p>Written by Aditya Joshi &copy; Joshi's</p>
    </footer>
</body>

</html>